"""create users, properties, property_images, reports, inquiries

Revision ID: 325b432efd7e
Revises: 
Create Date: 2026-09-22 13:01:56.835638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325b432efd7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('propietario', 'buscador', name='user_role'), nullable=False),
    sa.Column('declaration_titular', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(email) > 3', name='ck_users_email_min_length'),
    sa.CheckConstraint('length(first_name) > 0', name='ck_users_first_name_not_empty'),
    sa.CheckConstraint('length(last_name) > 0', name='ck_users_last_name_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.Enum('alquiler_permanente', 'alquiler_temporal', 'venta', name='operation_type'), nullable=False),
    sa.Column('property_type', sa.Enum('casa', 'departamento', 'terreno', 'salon_comercial', name='property_type'), nullable=False),
    sa.Column('status', sa.Enum('disponible', 'en_negociacion', 'finalizada', name='property_status'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('ARS', 'USD', name='property_currency'), nullable=False),
    sa.Column('monthly_fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('surface_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('has_water', sa.Boolean(), nullable=False),
    sa.Column('has_electricity', sa.Boolean(), nullable=False),
    sa.Column('has_sewage', sa.Boolean(), nullable=False),
    sa.Column('has_gas', sa.Boolean(), nullable=False),
    sa.Column('has_internet', sa.Boolean(), nullable=False),
    sa.Column('contact_whatsapp', sa.String(length=30), nullable=True),
    sa.Column('allow_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('bathrooms >= 0', name='ck_properties_bathrooms_non_negative'),
    sa.CheckConstraint('bedrooms >= 0', name='ck_properties_bedrooms_non_negative'),
    sa.CheckConstraint('length(description) >= 10', name='ck_properties_description_min_length'),
    sa.CheckConstraint('length(title) >= 3', name='ck_properties_title_min_length'),
    sa.CheckConstraint('monthly_fees IS NULL OR monthly_fees >= 0', name='ck_properties_fees_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_properties_price_non_negative'),
    sa.CheckConstraint('surface_m2 IS NULL OR surface_m2 > 0', name='ck_properties_surface_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_neighborhood'), 'properties', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.create_index(op.f('ix_properties_price'), 'properties', ['price'], unique=False)
    op.create_index('ix_properties_search', 'properties', ['status', 'operation_type', 'property_type'], unique=False)
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_property_id'), 'inquiries', ['property_id'], unique=False)
    op.create_index(op.f('ix_inquiries_sender_id'), 'inquiries', ['sender_id'], unique=False)
    op.create_table('property_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_images_property_id'), 'property_images', ['property_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('spam', 'intermediario_real', 'datos_falsos', 'duplicada', 'otro', name='report_reason'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pendiente', 'revisado', 'rechazado', name='report_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_property_id'), 'reports', ['property_id'], unique=False)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index(op.f('ix_reports_property_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_property_images_property_id'), table_name='property_images')
    op.drop_table('property_images')
    op.drop_index(op.f('ix_inquiries_sender_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_property_id'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index('ix_properties_search', table_name='properties')
    op.drop_index(op.f('ix_properties_price'), table_name='properties')
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_neighborhood'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
